version: '3'
services:
  backstage:
    image: backstage:v4
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      # Add your token here
      GITHUB_TOKEN: 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
    ports:
      - '7007:7007'

  db:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust