version: 2.1
orbs:
  # https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@5.0.3
  
  # https://circleci.com/developer/orbs/orb/circleci/aws-ecr
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  build:
    executor:
     name: node/default
     tag: 16.19.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: Build container image
          command: |
            # Build the container image
            ls -lrt /home/circleci/project/
            cd /home/circleci/project/
            # docker build -t my-image .
            # yarn install
            # yarn tsc
            DOCKER_BUILDKIT=1 yarn build-image

      - run:
          name: Login to AWS ECR
          command: |
            # Authenticate with AWS ECR
            docker login -u AWS -p "$(aws ecr get-login-password)" "https://$(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.us-east-1.amazonaws.com"
            $(aws ecr get-login --no-include-email --region us-east-1)

      - run:
          name: Push container image to ECR
          command: |
            # Tag the container image and push it to ECR
            REPOSITORY_URL=$(aws ecr describe-repositories --repository-names my-repository --region us-east-1 | jq -r '.repositories[0].repositoryUri')
            docker tag my-image:latest $REPOSITORY_URL:latest
            docker push $REPOSITORY_URL:latest
