version: 2.1
orbs:
  # https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@5.0.3
  
  # https://circleci.com/developer/orbs/orb/circleci/aws-ecr
  aws-ecr: circleci/aws-ecr@8.2.1
jobs:
  test:
    executor:
      name: node/default
      tag: 16.19.0
    steps:
    - checkout
    - setup_remote_docker:
        version: 20.10.14
    - run: |
        # node --version
        # yarn --version
        # docker --version
        # yarn build
        # yarn install --frozen-lockfile
        ls -lrt
        # DOCKER_BUILDKIT=1 yarn workspace backend build-image
        yarn install
        #DOCKER_BUILDKIT=1 yarn build-image
    - node/install-packages:
        pkg-manager: yarn
    # - checkout
    # - run: |
    #     node --version
    # - store_artifacts:
    #     path: /tmp/test-results
    #     destination: raw-test-output
    # - store_test_results:
    #     path: /tmp/test-results
workflows:
  node-tests:
    jobs:
    - test
    # Envs: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION, AWS_ECR_ACCOUNT_URL
    - aws-ecr/build-and-push-image:
        repo: backstage-image
        tag: "latest,v0.1.${CIRCLE_BUILD_NUM}"
        dockerfile: packages/backend/Dockerfile
        path: .
        requires:
          - test